name: Add Text to Markdown Files

# Dispara a ação manualmente ou em um push
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write  # Permissões para modificar e fazer push no repositório

jobs:
  add-text-to-markdown:
    runs-on: ubuntu-latest

    steps:
    # Checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Definir o texto a ser adicionado e aplicar em todos os arquivos .md
    - name: Add text to markdown files
      run: |
        # Texto que será adicionado no final dos arquivos .md
        TEXT_TO_ADD='<hr><p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://davifma.github.io/proMpto/">prompto.github.io</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="http://linkedin.com/in/davifma">Davi Fontebasso Marques de Almeida</a> is licensed under <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Creative Commons Attribution 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""> <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a></p>'

        # Encontra todos os arquivos .md e adiciona o texto se ele ainda não estiver presente
        find . -type f -name "*.md" | while read FILE
        do
          # Verifica se o arquivo já contém o texto
          if ! grep -qF "$TEXT_TO_ADD" "$FILE"; then
            # Adiciona o texto ao final do arquivo
            echo -e "$TEXT_TO_ADD" >> "$FILE"
          fi
        done

    # Commit das mudanças e push de volta para o repositório
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Verifica se há mudanças a serem commitadas
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "Added predefined text to all markdown files"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
