name: Add Text to Newly Created Markdown Files

# Ação será executada quando um push for realizado no repositório
on:
  push:
    paths:
      - '**/*.md'  # Monitora mudanças em todos os arquivos .md

permissions:
  contents: write  # Garante permissões para fazer push no repositório

jobs:
  add-text-to-new-md:
    runs-on: ubuntu-latest

    steps:
    # Primeiro passo: checkout do repositório para trabalhar com os arquivos
    - name: Checkout repository
      uses: actions/checkout@v3

    # Verifica arquivos .md recém-criados e adiciona texto no final
    - name: Add text to newly created markdown files
      run: |
        # Texto a ser adicionado no final dos novos arquivos .md
        TEXT_TO_ADD='<hr><p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://davifma.github.io/proMpto/">prompto.github.io</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="http://linkedin.com/in/davifma">Davi Fontebasso Marques de Almeida</a> is licensed under <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Creative Commons Attribution 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""> <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a></p>'

        # Verifica arquivos .md adicionados no último commit
        git diff --name-status HEAD^ HEAD | grep "^A" | grep ".md" | awk '{print $2}' | while read FILE
        do
          # Adiciona o texto ao final do arquivo recém-criado
          echo -e "$TEXT_TO_ADD" >> "$FILE"
        done

    # Commit e push das mudanças para o repositório
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Verifica se há mudanças a serem commitadas
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "Added predefined text to newly created markdown files"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
