name: Trocar Palavras

# Define quando a Action será executada. Nesse caso, ela é executada manualmente através do "workflow_dispatch"
on:
  workflow_dispatch:

jobs:
  replace-words:
    # Definindo o ambiente de execução como Ubuntu (Linux)
    runs-on: ubuntu-latest

    steps:
    # Primeiro passo: Checa o repositório atual no ambiente do runner
    - name: Check out the repository
      uses: actions/checkout@v3

    # Passo 2: Substitui palavras em todos os arquivos .md
    - name: Find and replace words in Markdown files
      run: |
        # Define as palavras que você quer substituir
        OLD_WORD="prompt"  # Substitua por sua palavra antiga
        NEW_WORD="proMpt"    # Substitua pela nova palavra

        # Procura todos os arquivos .md no repositório
        find . -type f -name "*.md" | while read FILE
        do
          # Usa 'sed' para substituir as palavras nos arquivos .md
          sed -i "s/$OLD_WORD/$NEW_WORD/g" "$FILE"
        done

    # Passo 3: Comitar as mudanças no repositório
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Replaced '$OLD_WORD' with '$NEW_WORD' in all markdown files"
        git push
      env:
        # Necessário para autorizar o push no repositório
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
