name: Trocar Palavras

# Define quando a Action será executada. Aqui é manualmente, mas pode ser alterado para outros eventos
on:
  workflow_dispatch:

permissions:
  contents: write  # Garante permissões para fazer push no repositório

jobs:
  replace-words:
    runs-on: ubuntu-latest

    steps:
    # Primeiro passo: Checa o repositório atual no ambiente do runner
    - name: Check out the repository
      uses: actions/checkout@v3

    # Passo 2: Substitui palavras em todos os arquivos .md
    - name: Find and replace words in Markdown files
      run: |
        OLD_WORD="00002.png"  # Substitua pela palavra antiga
        NEW_WORD="002.png"    # Substitua pela nova palavra

        # Procura todos os arquivos .md no repositório e substitui as palavras
        find . -type f -name "*.md" | while read FILE
        do
          sed -i "s/$OLD_WORD/$NEW_WORD/g" "$FILE"
        done

    # Passo 3: Commit e push das mudanças (se houver)
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Verifica se há mudanças a serem commitadas
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "Replaced '$OLD_WORD' with '$NEW_WORD' in all markdown files"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
